// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NSPC.Data.Data;

#nullable disable

namespace NSPC.Data.Migrations
{
    [DbContext(typeof(SMDbContext))]
    [Migration("20240604021514_fix-public-vỉtual")]
    partial class fixpublicvỉtual
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NSPC.Data.bsd_KeyValue", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("bsd_Key_Value");
                });

            modelBuilder.Entity("NSPC.Data.BsdNavigation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HasChild")
                        .HasColumnType("boolean");

                    b.Property<string>("IconClass")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdPath")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)");

                    b.Property<string>("QueryParams")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("SubUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UrlRewrite")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("bsd_Navigation");
                });

            modelBuilder.Entity("NSPC.Data.BsdNavigationMapRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("FromSubNavigation")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NavigationId");

                    b.ToTable("bsd_Navigation_Map_Role");
                });

            modelBuilder.Entity("NSPC.Data.BsdParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("bsd_Parameter");
                });

            modelBuilder.Entity("NSPC.Data.cata_Commune", b =>
                {
                    b.Property<int>("CommuneCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommuneCode"));

                    b.Property<string>("CommuneName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DistrictCode")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictId_VP")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OldVTPName")
                        .HasColumnType("text");

                    b.Property<string>("VNPAsciiName")
                        .HasColumnType("text");

                    b.Property<string>("VTPAsciiName")
                        .HasColumnType("text");

                    b.Property<int>("VnpostSyncStatus")
                        .HasColumnType("integer");

                    b.Property<int>("WardId_VP")
                        .HasColumnType("integer");

                    b.Property<string>("WardName_VP")
                        .HasColumnType("text");

                    b.HasKey("CommuneCode");

                    b.ToTable("cata_Commune");
                });

            modelBuilder.Entity("NSPC.Data.cata_District", b =>
                {
                    b.Property<int>("DistrictCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DistrictCode"));

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DelayShipFromDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DelayShipToDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DistrictId_VP")
                        .HasColumnType("integer");

                    b.Property<string>("DistrictName")
                        .HasColumnType("text");

                    b.Property<string>("DistrictName_VP")
                        .HasColumnType("text");

                    b.Property<int>("DistrictShippingType")
                        .HasColumnType("integer");

                    b.Property<string>("DistrictValue_VP")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProvinceCode")
                        .HasColumnType("integer");

                    b.Property<int>("ProvinceId_VP")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StopShipFromDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StopShipToDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VnpostSyncStatus")
                        .HasColumnType("integer");

                    b.HasKey("DistrictCode");

                    b.ToTable("cata_District");
                });

            modelBuilder.Entity("NSPC.Data.cata_Province", b =>
                {
                    b.Property<int>("ProvinceCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProvinceCode"));

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DelayShipFromDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DelayShipToDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("ProvinceCode_VP")
                        .HasColumnType("text");

                    b.Property<int>("ProvinceId_VP")
                        .HasColumnType("integer");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("text");

                    b.Property<string>("ProvinceName_VP")
                        .HasColumnType("text");

                    b.Property<int>("ProvinceShippingType")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceType_VP")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StopShipFromDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StopShipToDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TotalDistrictShipDelay")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDistrictShipStop")
                        .HasColumnType("integer");

                    b.HasKey("ProvinceCode");

                    b.ToTable("cata_Province");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.ActivityHistory.sm_ActiviyHisroty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("sm_ActiviyHisroty");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.BaoGia.mk_BaoGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("IdDuAn")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TongTien")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDuAn");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("mk_BaoGia");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.BaoGiaItem.mk_BaoGiaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaoGiaType")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DonGia")
                        .HasColumnType("text");

                    b.Property<string>("DonVi")
                        .HasColumnType("text");

                    b.Property<Guid>("IdBaoGia")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdVatTu")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SoLuong")
                        .HasColumnType("text");

                    b.Property<string>("TongTien")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdBaoGia");

                    b.HasIndex("IdSanPham");

                    b.HasIndex("IdVatTu");

                    b.ToTable("mk_BaoGiaItem");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.Bom.mk_Bom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaBom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdSanPham");

                    b.ToTable("mk_Bom");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.ChiPhi.mk_ChiPhi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChiChoMucDich")
                        .HasColumnType("text");

                    b.Property<string>("ChiPhiType")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<Guid>("IdDuAn")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdMaNhaCungCap")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaChi")
                        .HasColumnType("text");

                    b.Property<string>("SoTien")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDuAn");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdMaNhaCungCap");

                    b.ToTable("mk_ChiPhi");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.ChucVu.mk_ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mk_ChucVu");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.DuAn.mk_DuAn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaDuAn")
                        .HasColumnType("text");

                    b.Property<string>("TenDuAn")
                        .HasColumnType("text");

                    b.Property<string>("TongHopChi")
                        .HasColumnType("text");

                    b.Property<string>("TongHopThu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mk_DuAn");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.NguyenVatLieu.mk_NguyenVatLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DonGia")
                        .HasColumnType("text");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("text");

                    b.Property<Guid>("IdBom")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdVatTu")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaNguyenVatLieu")
                        .HasColumnType("text");

                    b.Property<string>("SoLuong")
                        .HasColumnType("text");

                    b.Property<string>("TenNguyenVatLieu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdBom");

                    b.HasIndex("IdVatTu");

                    b.ToTable("mk_NguyenVatLieu");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.NhaCungCap.mk_NhaCungCap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaNhaCungCap")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.Property<string>("TenNhaCungCap")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mk_NhaCungCap");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.NhomVatTu.mk_NhomVatTu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mk_NhomVatTu");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.PhongBan.mk_PhongBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaPhongBan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mk_PhongBan");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.QuanLyKho.mk_QuanLyKho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GiaTien")
                        .HasColumnType("text");

                    b.Property<Guid>("IdDuAn")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdNhaCungCap")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdVatTu")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LoaiPhieu")
                        .HasColumnType("text");

                    b.Property<string>("MaDonHang")
                        .HasColumnType("text");

                    b.Property<string>("MaKho")
                        .HasColumnType("text");

                    b.Property<string>("MucDichNhapKho")
                        .HasColumnType("text");

                    b.Property<string>("SoLuong")
                        .HasColumnType("text");

                    b.Property<string>("TongTien")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdDuAn");

                    b.HasIndex("IdNhaCungCap");

                    b.HasIndex("IdVatTu");

                    b.ToTable("mk_QuanLyKho");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.SanPham.mk_SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DonGia")
                        .HasColumnType("text");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mk_SanPham");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.VatTu.mk_VatTu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("HinhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("HinhDinhKem")
                        .HasColumnType("text");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaVatTu")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenVatTu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("mk_VatTu");
                });

            modelBuilder.Entity("NSPC.Data.erp_Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CopyRight")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocType")
                        .HasColumnType("text");

                    b.Property<string>("DocTypeName")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("License")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("StatusCode")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("UpdateFrequency")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("erp_Attachment");
                });

            modelBuilder.Entity("NSPC.Data.idm_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActiveDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("BankAccountNo")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("BankUsername")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailVerifyToken")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FacebookUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("GoogleUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Password")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PlainTextPwd")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<List<string>>("RoleListCode")
                        .HasColumnType("text[]");

                    b.Property<string>("StatusCode")
                        .HasColumnType("text");

                    b.Property<string>("UpdateLog")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("idm_User");
                });

            modelBuilder.Entity("NSPC.Data.IdmRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("idm_Role");
                });

            modelBuilder.Entity("NSPC.Data.sm_CodeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("TranslationCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("sm_CodeType");
                });

            modelBuilder.Entity("NSPC.Data.sm_CodeType_Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodeTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodeTypeId");

                    b.ToTable("sm_CodeType_Translation");
                });

            modelBuilder.Entity("NSPC.Data.sm_Email_Subscribe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SubscribeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TotalEmailSentCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnsubscribeDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("sm_Email_Subscribe");
                });

            modelBuilder.Entity("NSPC.Data.sm_Email_Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("sm_Email_Template");
                });

            modelBuilder.Entity("NSPC.Data.sm_Email_Template_Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyTemplate")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmailTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TitleTemplate")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("sm_Email_Template_Translations");
                });

            modelBuilder.Entity("NSPC.Data.sm_Email_Verification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ValidDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VerifyToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("sm_Email_Verification");
                });

            modelBuilder.Entity("NSPC.Data.sm_KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastCareOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LinkFacebook")
                        .HasColumnType("text");

                    b.Property<string>("LinkTelegram")
                        .HasColumnType("text");

                    b.Property<string>("LinkTiktok")
                        .HasColumnType("text");

                    b.Property<List<string>>("LoaiKhachHang")
                        .HasColumnType("text[]");

                    b.Property<string>("Ma")
                        .HasColumnType("text");

                    b.Property<string>("NhuCauBanDau")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.Property<string>("Ten")
                        .HasColumnType("text");

                    b.Property<int>("TotalCareTimes")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("sm_KhachHang");
                });

            modelBuilder.Entity("NSPC.Data.sm_LichSuChamSoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DanhGia")
                        .HasColumnType("integer");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModifiedByUserName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("KhachHangId");

                    b.ToTable("sm_LichSuChamSoc");
                });

            modelBuilder.Entity("NSPC.Data.sm_Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsReceiverRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReceiverSeen")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonData")
                        .HasColumnType("text");

                    b.Property<string>("JsonDataType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ReceiverReadOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ReceiverUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ReceiverUserId");

                    b.ToTable("sm_Notification");
                });

            modelBuilder.Entity("NSPC.Data.sm_Notification_Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("sm_Notification_Template");
                });

            modelBuilder.Entity("NSPC.Data.sm_Notification_Template_Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyHtmlTemplate")
                        .HasColumnType("text");

                    b.Property<string>("BodyPlainTextTemplate")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Language")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("LastModifiedOnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("NotificationTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TitleTemplate")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTemplateId");

                    b.ToTable("sm_Notification_Template_Translation");
                });

            modelBuilder.Entity("NSPC.Data.BsdNavigation", b =>
                {
                    b.HasOne("NSPC.Data.BsdNavigation", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NSPC.Data.BsdNavigationMapRole", b =>
                {
                    b.HasOne("NSPC.Data.BsdNavigation", "Navigation")
                        .WithMany("NavigationRole")
                        .HasForeignKey("NavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Navigation");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.BaoGia.mk_BaoGia", b =>
                {
                    b.HasOne("NSPC.Data.Data.Entity.DuAn.mk_DuAn", "mk_DuAn")
                        .WithMany("mk_BaoGia")
                        .HasForeignKey("IdDuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSPC.Data.sm_KhachHang", "sm_KhachHang")
                        .WithMany("mk_BaoGia")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mk_DuAn");

                    b.Navigation("sm_KhachHang");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.BaoGiaItem.mk_BaoGiaItem", b =>
                {
                    b.HasOne("NSPC.Data.Data.Entity.BaoGia.mk_BaoGia", "mk_BaoGia")
                        .WithMany("mk_BaoGiaItem")
                        .HasForeignKey("IdBaoGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSPC.Data.Data.Entity.SanPham.mk_SanPham", "mk_SanPham")
                        .WithMany()
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSPC.Data.Data.Entity.VatTu.mk_VatTu", "mk_VatTu")
                        .WithMany("mk_BaoGiaItem")
                        .HasForeignKey("IdVatTu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mk_BaoGia");

                    b.Navigation("mk_SanPham");

                    b.Navigation("mk_VatTu");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.Bom.mk_Bom", b =>
                {
                    b.HasOne("NSPC.Data.Data.Entity.SanPham.mk_SanPham", "mk_SanPham")
                        .WithMany()
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mk_SanPham");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.ChiPhi.mk_ChiPhi", b =>
                {
                    b.HasOne("NSPC.Data.Data.Entity.DuAn.mk_DuAn", "mk_DuAn")
                        .WithMany("mk_ChiPhi")
                        .HasForeignKey("IdDuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSPC.Data.sm_KhachHang", "sm_KhachHang")
                        .WithMany("mk_ChiPhi")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSPC.Data.Data.Entity.NhaCungCap.mk_NhaCungCap", "mk_NhaCungCap")
                        .WithMany("mk_ChiPhi")
                        .HasForeignKey("IdMaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mk_DuAn");

                    b.Navigation("mk_NhaCungCap");

                    b.Navigation("sm_KhachHang");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.NguyenVatLieu.mk_NguyenVatLieu", b =>
                {
                    b.HasOne("NSPC.Data.Data.Entity.Bom.mk_Bom", "mk_Bom")
                        .WithMany("NguyenVatLieu")
                        .HasForeignKey("IdBom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSPC.Data.Data.Entity.VatTu.mk_VatTu", "mk_VatTu")
                        .WithMany("mk_NguyenVatLieu")
                        .HasForeignKey("IdVatTu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mk_Bom");

                    b.Navigation("mk_VatTu");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.QuanLyKho.mk_QuanLyKho", b =>
                {
                    b.HasOne("NSPC.Data.Data.Entity.DuAn.mk_DuAn", "mk_DuAn")
                        .WithMany("mk_QuanLyKho")
                        .HasForeignKey("IdDuAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSPC.Data.Data.Entity.NhaCungCap.mk_NhaCungCap", "mk_NhaCungCap")
                        .WithMany("mk_QuanLyKho")
                        .HasForeignKey("IdNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSPC.Data.Data.Entity.VatTu.mk_VatTu", "mk_VatTu")
                        .WithMany()
                        .HasForeignKey("IdVatTu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mk_DuAn");

                    b.Navigation("mk_NhaCungCap");

                    b.Navigation("mk_VatTu");
                });

            modelBuilder.Entity("NSPC.Data.sm_CodeType_Translation", b =>
                {
                    b.HasOne("NSPC.Data.sm_CodeType", "ub_CodeType")
                        .WithMany("sm_CodeType_Translation")
                        .HasForeignKey("CodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ub_CodeType");
                });

            modelBuilder.Entity("NSPC.Data.sm_Email_Template_Translation", b =>
                {
                    b.HasOne("NSPC.Data.sm_Email_Template", "sm_Email_Template")
                        .WithMany("sm_Email_Template_Translation")
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sm_Email_Template");
                });

            modelBuilder.Entity("NSPC.Data.sm_KhachHang", b =>
                {
                    b.HasOne("NSPC.Data.idm_User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("NSPC.Data.sm_LichSuChamSoc", b =>
                {
                    b.HasOne("NSPC.Data.idm_User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSPC.Data.sm_KhachHang", "sm_KhachHang")
                        .WithMany("sm_LichSuChamSoc")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("sm_KhachHang");
                });

            modelBuilder.Entity("NSPC.Data.sm_Notification", b =>
                {
                    b.HasOne("NSPC.Data.idm_User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NSPC.Data.idm_User", "ReceiverUser")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CreatedByUser");

                    b.Navigation("ReceiverUser");
                });

            modelBuilder.Entity("NSPC.Data.sm_Notification_Template_Translation", b =>
                {
                    b.HasOne("NSPC.Data.sm_Notification_Template", "ub_Notification_Template")
                        .WithMany("Translations")
                        .HasForeignKey("NotificationTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ub_Notification_Template");
                });

            modelBuilder.Entity("NSPC.Data.BsdNavigation", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("NavigationRole");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.BaoGia.mk_BaoGia", b =>
                {
                    b.Navigation("mk_BaoGiaItem");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.Bom.mk_Bom", b =>
                {
                    b.Navigation("NguyenVatLieu");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.DuAn.mk_DuAn", b =>
                {
                    b.Navigation("mk_BaoGia");

                    b.Navigation("mk_ChiPhi");

                    b.Navigation("mk_QuanLyKho");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.NhaCungCap.mk_NhaCungCap", b =>
                {
                    b.Navigation("mk_ChiPhi");

                    b.Navigation("mk_QuanLyKho");
                });

            modelBuilder.Entity("NSPC.Data.Data.Entity.VatTu.mk_VatTu", b =>
                {
                    b.Navigation("mk_BaoGiaItem");

                    b.Navigation("mk_NguyenVatLieu");
                });

            modelBuilder.Entity("NSPC.Data.sm_CodeType", b =>
                {
                    b.Navigation("sm_CodeType_Translation");
                });

            modelBuilder.Entity("NSPC.Data.sm_Email_Template", b =>
                {
                    b.Navigation("sm_Email_Template_Translation");
                });

            modelBuilder.Entity("NSPC.Data.sm_KhachHang", b =>
                {
                    b.Navigation("mk_BaoGia");

                    b.Navigation("mk_ChiPhi");

                    b.Navigation("sm_LichSuChamSoc");
                });

            modelBuilder.Entity("NSPC.Data.sm_Notification_Template", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
